import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import {createWorld} from './world.js?v=4';
import {WORDS,readSave,writeSave,points,shuffle,terrainHeight,floorHeight,canStand,canStep} from './state.js?v=4';
const el=id=>document.getElementById(id);
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw new Error('Unavailable storage');}};}
const saved=readSave(storage),found=new Set(saved.found);let visited=saved.restaurant;
let started=false,modal=null,nearest=null,activeWord=null,answered=false,renderer,world;
let yaw=0,pitch=.36,zoom=7.5,jumpVelocity=0,jumpOffset=0,walkTime=0,runToggle=false,targetId=null;
let lastTime=performance.now(),lastDraw=0,lastUI=0,toastTimer,returnFocus=null,dialogueStep=0;
const keys=new Set(),touch={x:0,y:0},look={id:null,x:0,y:0},scene=new THREE.Scene();
scene.background=new THREE.Color(0x9fbfc0);scene.fog=new THREE.Fog(0xa6bdb5,75,215);
const camera=new THREE.PerspectiveCamera(57,innerWidth/innerHeight,.1,320);
const sunlight=new THREE.DirectionalLight(0xffe7ba,2.6);sunlight.position.set(-32,65,28);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);Object.assign(sunlight.shadow.camera,{left:-50,right:50,top:50,bottom:-50,near:.5,far:170});sunlight.shadow.bias=-.0004;sunlight.shadow.normalBias=.08;scene.add(sunlight);scene.add(sunlight.target);
const ambient=new THREE.HemisphereLight(0xcbe6e6,0x566542,1.8);scene.add(ambient);
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;}
catch{const {SoftwareRenderer}=await import('./software-renderer.js?v=4');renderer=new SoftwareRenderer();document.body.dataset.software='true';}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.domElement.setAttribute('aria-label','مشهد الوادي ثلاثي الأبعاد');renderer.domElement.tabIndex=0;el('game').appendChild(renderer.domElement);
world=createWorld(scene,{low:renderer.isSoftware||innerWidth<760});
const player=world.player.root;camera.position.set(12,9,46);camera.lookAt(0,3,-8);
const map=el('minimap').getContext('2d');
function toast(message){el('toast').textContent=message;el('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.remove('show'),3400);}
function speak(text){if(!('speechSynthesis'in window)){toast('النطق غير متاح في هذا المتصفح. يمكنك قراءة الكلمة ومعناها.');return;}try{const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.78;const voice=speechSynthesis.getVoices().find(v=>v.lang==='en-US');if(voice)u.voice=voice;speechSynthesis.cancel();speechSynthesis.speak(u);}catch{toast('تعذّر تشغيل النطق في هذا المتصفح.');}}
function persist(){if(!writeSave(storage,found,visited))toast('تعذّر حفظ التقدم على هذا الجهاز؛ تقدر تواصل اللعب.');updateHUD();}
function wordCount(){return WORDS.filter(w=>found.has(w.id)).length;}
function updateHUD(){const n=wordCount();el('xp').textContent=points(found);el('found').textContent=n+' / '+WORDS.length;el('missionBar').style.width=n/WORDS.length*100+'%';let title='خذ أول خطوة',text='اقترب من العلامات الذهبية واكتشف الكلمات.';if(n>=3&&!visited){title='على الضفة الأخرى';text='اعبر الجسر وامشِ إلى مطعم الوادي. بابه مفتوح لك.';}else if(visited&&n<WORDS.length){title='قصص جديدة، كلمات جديدة';text='استكشف المخيم والمطعم. بقيت '+(WORDS.length-n)+' كلمات في رحلتك.';}else if(n===WORDS.length){title='أنت مستكشف الوادي!';text='اكتشفت كل الكلمات. راجعها من كلماتي، واستمتع بالتجول.';}el('missionTitle').textContent=title;el('missionText').textContent=text;world?.markers.forEach(m=>m.group.visible=!found.has(m.word.id));}
function clearMovement(){keys.clear();touch.x=touch.y=0;look.id=null;el('knob').style.transform='translate(0,0)';}
function openModal(id){if(modal)closeModal();modal=id;clearMovement();returnFocus=document.activeElement;el(id).classList.remove('hidden');el('prompt').classList.add('hidden');const first=el(id).querySelector('button:not([disabled]),select');first?.focus();}
function closeModal(){if(!modal)return;el(modal).classList.add('hidden');modal=null;activeWord=null;answered=false;if('speechSynthesis'in window)speechSynthesis.cancel();(returnFocus?.isConnected?returnFocus:renderer.domElement).focus({preventScroll:true});}
function isInside(x=player.position.x,z=player.position.z){return x>12.8&&x<27.2&&z>-28.8&&z<-15.3;}
function openQuiz(word){activeWord=word;openModal('quiz');activeWord=word;answered=false;el('questionTitle').textContent="What's this?";el('objectHint').textContent='أنت أمام '+word.ar+' — ما اسمها بالإنجليزية؟';el('feedback').textContent='';el('continueBtn').classList.add('hidden');const answers=el('answers');answers.replaceChildren();for(const option of shuffle(word.choices)){const button=document.createElement('button');button.className='answer';button.textContent=option;button.onclick=()=>answer(button,option,word);answers.appendChild(button);}}
function answer(button,option,word){if(answered||activeWord?.id!==word.id)return;if(option!==word.word){button.classList.add('wrong');button.disabled=true;el('feedback').textContent='حاول مرة ثانية، أو اضغط «اسمع الكلمة» للمساعدة.';return;}answered=true;const fresh=!found.has(word.id);found.add(word.id);button.classList.add('correct');el('answers').querySelectorAll('button').forEach(b=>b.disabled=true);el('feedback').textContent=word.word+' = '+word.ar+(fresh?' · +10 XP':' · مراجعة موفّقة');el('objectHint').textContent=word.sentence;el('continueBtn').classList.remove('hidden');persist();speak(word.word);if(targetId===word.id)targetId=null;el('continueBtn').focus();}
function showJournal(){el('wordList').replaceChildren();for(const w of WORDS){const known=found.has(w.id),button=document.createElement('button');button.className='word-card'+(known?'':' locked');button.disabled=!known;const b=document.createElement('b'),span=document.createElement('span');b.textContent=known?w.word:'?';span.textContent=known?w.ar:'لم تُكتشف بعد';button.append(b,span);button.onclick=()=>speak(w.word);el('wordList').appendChild(button);}openModal('journal');}
const conversations=[{en:'Hello! Welcome to the valley café.',ar:'مرحبًا! أهلًا بك في مقهى الوادي.',options:['Hello!','Hi, how are you?']},{en:'I am well, thank you. What would you like?',ar:'أنا بخير، شكرًا لك. ماذا تود أن تطلب؟',options:['A cup of tea, please.','Some water, please.']},{en:'Of course. Would you like something to eat?',ar:'بالتأكيد. هل ترغب بشيء تأكله؟',options:['Yes, a sandwich, please.','No, thank you.']},{en:'Enjoy your visit! Have a wonderful day.',ar:'استمتع بزيارتك! أتمنى لك يومًا جميلًا.',options:['Thank you. Goodbye!']}];
function renderDialogue(){const line=conversations[dialogueStep];el('dialogueEn').textContent=line.en;el('dialogueAr').textContent=line.ar;el('dialogueOptions').replaceChildren();for(const response of line.options){const b=document.createElement('button');b.textContent=response;b.onclick=()=>{speak(response);if(dialogueStep===conversations.length-1){closeModal();toast('أحسنت! أكملت محادثتك في المطعم.');}else{dialogueStep++;renderDialogue();}};el('dialogueOptions').appendChild(b);}}
function interact(){if(!started||modal||!nearest)return;if(nearest.id==='waiter'){dialogueStep=0;renderDialogue();openModal('dialogue');}else openQuiz(nearest);}
function jump(){if(started&&!modal&&jumpOffset===0){jumpVelocity=6.3;jumpOffset=.001;}}
function updateInteraction(){if(!started||modal)return;const inside=isInside();if(inside&&!visited){visited=true;found.add('restaurant');persist();toast('وصلت إلى مطعم الوادي · +25 XP');}let best=null,dist=Infinity;for(const word of WORDS){if(found.has(word.id)||Boolean(word.indoor)!==inside)continue;const d=Math.hypot(player.position.x-word.x,player.position.z-word.z);if(d<word.r&&d<dist){dist=d;best=word;}}if(inside&&Math.hypot(player.position.x-24,player.position.z+26)<3.1&&!best)best={id:'waiter',ar:'تحدث مع موظف المطعم'};nearest=best;el('prompt').classList.toggle('hidden',!best);if(best)el('promptText').textContent=best.id==='waiter'?best.ar:'اكتشف '+best.ar;el('zone').textContent=inside?'مطعم الوادي':player.position.x<-10&&player.position.z<-8?'المخيم والغابة':'وادي الجبال';el('coordinates').textContent=Math.round(player.position.x)+' · '+Math.round(-player.position.z);const degrees=((yaw*180/Math.PI)%360+360)%360;el('heading').textContent=['N','NW','W','SW','S','SE','E','NE'][Math.round(degrees/45)%8];}
function hint(){const inside=isInside();let candidates=WORDS.filter(w=>!found.has(w.id));if(!candidates.length){toast('أكملت كل الكلمات! افتح كلماتي لمراجعتها.');return;}candidates.sort((a,b)=>Math.hypot(a.x-player.position.x,a.z-player.position.z)-Math.hypot(b.x-player.position.x,b.z-player.position.z));const w=candidates.find(w=>Boolean(w.indoor)===inside)||candidates[0];targetId=w.id;toast((w.indoor&&!inside?'ادخل المطعم، ثم ابحث عن ':'اتبع العلامة على الخريطة إلى ')+w.ar);}
function move(dt){if(!started||modal)return;let f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touch.y,r=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.x;const len=Math.hypot(f,r),speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')||runToggle)?9:4.7;let moving=false;if(len>.08){f/=Math.max(1,len);r/=Math.max(1,len);const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*r)*speed*dt,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*r)*speed*dt;const ox=player.position.x,oz=player.position.z;const permitted=(x,z)=>canStep(x,z,player.position.x,player.position.z,world.obstacles);if(permitted(ox+dx,oz))player.position.x+=dx;if(permitted(player.position.x,oz+dz))player.position.z+=dz;moving=Math.hypot(player.position.x-ox,player.position.z-oz)>.001;const targetAngle=Math.atan2(-dx,-dz);const delta=Math.atan2(Math.sin(targetAngle-player.rotation.y),Math.cos(targetAngle-player.rotation.y));player.rotation.y+=delta*Math.min(1,dt*14);}
 if(jumpOffset>0){jumpVelocity-=17*dt;jumpOffset=Math.max(0,jumpOffset+jumpVelocity*dt);}player.position.y=floorHeight(player.position.x,player.position.z)+jumpOffset;world.player.shadow.visible=jumpOffset<.15;walkTime+=dt;world.animate(walkTime,moving,speed,isInside());}
const cameraTarget=new THREE.Vector3(),desiredCamera=new THREE.Vector3(),eye=new THREE.Vector3();
function follow(dt){if(!started){const t=performance.now()*.00003;desiredCamera.set(9+Math.sin(t)*5,8.5,44);camera.position.lerp(desiredCamera,1-Math.exp(-dt*2));camera.lookAt(-3,3,-10);return;}cameraTarget.copy(player.position).add(new THREE.Vector3(0,1.5,0));const dist=isInside()?Math.min(zoom,4.3):zoom;desiredCamera.copy(cameraTarget).add(new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*dist,Math.sin(pitch)*dist,Math.cos(yaw)*Math.cos(pitch)*dist));
 // Keep the camera outside walls. Ignore low furniture for this camera sweep.
 for(let s=1;s<=18;s++){const t=s/18;eye.lerpVectors(cameraTarget,desiredCamera,t);const hit=world.obstacles.some(o=>o.kind==='box'&&(o.x2-o.x1<.8||o.z2-o.z1<.8)&&eye.y<5.9&&eye.x>o.x1-.15&&eye.x<o.x2+.15&&eye.z>o.z1-.15&&eye.z<o.z2+.15);if(hit){desiredCamera.lerpVectors(cameraTarget,desiredCamera,Math.max(.18,t-.08));break;}}
 desiredCamera.y=Math.max(desiredCamera.y,floorHeight(desiredCamera.x,desiredCamera.z)+.45);camera.position.lerp(desiredCamera,1-Math.exp(-dt*9));camera.lookAt(cameraTarget);sunlight.position.set(player.position.x-32,65,player.position.z+28);sunlight.target.position.copy(player.position);}
function drawMap(){const ctx=map,n=200,toX=x=>100+x*1.34,toY=z=>100+z*1.34;ctx.clearRect(0,0,n,n);ctx.fillStyle='#41573e';ctx.fillRect(0,0,n,n);ctx.fillStyle='#586c49';for(let x=0;x<200;x+=14)for(let y=0;y<200;y+=14){if(x<52||x>143){ctx.beginPath();ctx.moveTo(x,y+12);ctx.lineTo(x+6,y);ctx.lineTo(x+12,y+12);ctx.fill();}}ctx.strokeStyle='#ab9b71';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(100,193);ctx.lineTo(100,16);ctx.stroke();ctx.fillStyle='#65999c';ctx.fillRect(0,toY(2.5),200,15);ctx.fillStyle='#d2b98d';ctx.fillRect(toX(-3),toY(-.7),8,24);ctx.fillStyle='#d6c29a';ctx.fillRect(toX(12),toY(-29),21,19);ctx.fillStyle='#bc9963';ctx.beginPath();ctx.moveTo(toX(-25),toY(-21));ctx.lineTo(toX(-21),toY(-26));ctx.lineTo(toX(-17),toY(-21));ctx.fill();for(const word of WORDS){ctx.beginPath();ctx.arc(toX(word.x),toY(word.z),word.id===targetId?4.5:2.3,0,Math.PI*2);ctx.fillStyle=found.has(word.id)?'#8fae83':word.id===targetId?'#fff1b7':'#e4bf74';ctx.fill();if(word.id===targetId){ctx.strokeStyle='#ffe9b5';ctx.lineWidth=1;ctx.beginPath();ctx.arc(toX(word.x),toY(word.z),7,0,Math.PI*2);ctx.stroke();}}
 ctx.save();ctx.translate(toX(player.position.x),toY(player.position.z));ctx.rotate(-yaw);ctx.fillStyle='#fff4d8';ctx.strokeStyle='#203b31';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-4,4);ctx.lineTo(0,2);ctx.lineTo(4,4);ctx.closePath();ctx.stroke();ctx.fill();ctx.restore();}
function renderTarget(){const label=el('targetLabel');const word=WORDS.find(w=>w.id===targetId);if(!word||modal||!started){label.classList.add('hidden');return;}const p=new THREE.Vector3(word.x,floorHeight(word.x,word.z)+3.3,word.z).project(camera);const visible=p.z<1&&Math.abs(p.x)<.9&&Math.abs(p.y)<.8;label.classList.toggle('hidden',!visible);if(visible){label.style.left=(p.x*.5+.5)*innerWidth+'px';label.style.top=(-p.y*.5+.5)*innerHeight+'px';label.textContent=word.ar+' · '+Math.round(Math.hypot(player.position.x-word.x,player.position.z-word.z))+' م';}}
function frame(now){requestAnimationFrame(frame);if(document.hidden){lastTime=now;return;}const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;move(dt);follow(dt);const t=now*.001;if(!started)world.animate(t,false,0,false);world.markers.forEach((m,i)=>{m.group.visible=!found.has(m.word.id)&&(Boolean(m.word.indoor)===isInside()||!started&&!m.word.indoor);m.group.position.y=m.baseY+Math.sin(t*2+i)*.12;m.orb.rotation.y=t*.8;m.group.scale.setScalar(m.word.id===targetId?1.4:1);});if(now-lastUI>120){updateInteraction();drawMap();renderTarget();lastUI=now;}if(!renderer.isSoftware||now-lastDraw>65){renderer.render(scene,camera);lastDraw=now;}}
function start(){if(started)return;started=true;el('startScreen').classList.add('hidden');el('playUI').classList.remove('hidden');player.position.set(0,0,34);yaw=0;pitch=.36;zoom=7.5;renderer.domElement.focus();updateHUD();toast('أهلًا بالمسافر! اقترب من اللافتة أمامك واضغط E.');}
el('startBtn').onclick=start;el('prompt').onclick=interact;el('jumpBtn').onclick=jump;el('runBtn').onclick=()=>{runToggle=!runToggle;el('runBtn').setAttribute('aria-pressed',String(runToggle));};el('journalBtn').onclick=showJournal;el('settingsBtn').onclick=()=>openModal('settings');el('resumeBtn').onclick=closeModal;el('closeQuiz').onclick=closeModal;el('continueBtn').onclick=closeModal;el('closeJournal').onclick=closeModal;el('closeDialogue').onclick=closeModal;el('listen').onclick=()=>activeWord&&speak(activeWord.word);el('dialogueListen').onclick=()=>speak(conversations[dialogueStep].en);el('hintBtn').onclick=hint;
el('homeBtn').onclick=()=>{player.position.set(0,0,34);yaw=0;pitch=.36;jumpOffset=jumpVelocity=0;closeModal();toast('رجعت إلى بداية الوادي. كلماتك محفوظة.');};
el('quality').onchange=e=>{const high=e.target.value==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.6:1));renderer.shadowMap.enabled=high&&!renderer.isSoftware;if(!renderer.isSoftware)renderer.shadowMap.needsUpdate=true;renderer.setSize(innerWidth,innerHeight);toast(high?'تفاصيل الرسومات عالية':'تم تخفيف الرسومات');};
el('timeOfDay').onchange=e=>{const sunset=e.target.value==='sunset';scene.background.set(sunset?0xb7a092:0x9fbfc0);scene.fog.color.set(sunset?0xbeb09a:0xa6bdb5);sunlight.color.set(sunset?0xffbe82:0xffe7ba);sunlight.intensity=sunset?2.1:2.6;ambient.intensity=sunset?1.25:1.8;toast(sunset?'وصل الغروب إلى الوادي':'صباح جديد في الوادي');};
const moveKeys=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'];
addEventListener('keydown',e=>{if(e.code==='Escape'&&started){e.preventDefault();modal?closeModal():openModal('settings');return;}if(modal){if(e.key==='Tab'){const focusable=[...el(modal).querySelectorAll('button:not([disabled]),select')].filter(n=>!n.closest('.hidden'));const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}return;}if(!started)return;if(moveKeys.includes(e.code)){keys.add(e.code);e.preventDefault();}if(e.code==='Space'){e.preventDefault();if(!e.repeat)jump();}if(e.code==='KeyE'&&!e.repeat){e.preventDefault();interact();}if(e.code==='KeyM'&&!e.repeat)showJournal();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',clearMovement);document.addEventListener('visibilitychange',clearMovement);
renderer.domElement.addEventListener('pointerdown',e=>{if(!started||modal||look.id!==null)return;look.id=e.pointerId;look.x=e.clientX;look.y=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==look.id||modal)return;yaw-=(e.clientX-look.x)*.005;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-look.y)*.004,.08,1.1);look.x=e.clientX;look.y=e.clientY;});const endLook=e=>{if(e.pointerId===look.id)look.id=null;};renderer.domElement.addEventListener('pointerup',endLook);renderer.domElement.addEventListener('pointercancel',endLook);renderer.domElement.addEventListener('lostpointercapture',endLook);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('wheel',e=>{if(!started||modal)return;e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.008,3.4,12);},{passive:false});
let joystickId=null;const joystick=el('joystick');function updateStick(e){const bounds=joystick.getBoundingClientRect(),max=bounds.width*.34;let x=e.clientX-bounds.left-bounds.width/2,y=e.clientY-bounds.top-bounds.height/2,len=Math.hypot(x,y);if(len>max){x=x/len*max;y=y/len*max;}touch.x=x/max;touch.y=-y/max;el('knob').style.transform=`translate(${x}px,${y}px)`;}
joystick.addEventListener('pointerdown',e=>{if(joystickId!==null||modal)return;joystickId=e.pointerId;joystick.setPointerCapture(e.pointerId);updateStick(e);e.preventDefault();});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickId)updateStick(e);});function endStick(e){if(e.pointerId!==joystickId)return;joystickId=null;touch.x=touch.y=0;el('knob').style.transform='translate(0,0)';}joystick.addEventListener('pointerup',endStick);joystick.addEventListener('pointercancel',endStick);joystick.addEventListener('lostpointercapture',endStick);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);clearMovement();});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();if(started)openModal('settings');toast('توقف عرض الرسومات. أعد تحميل الصفحة لاستعادة اللعبة؛ تقدمك محفوظ.');});
updateHUD();el('loadStatus').textContent=renderer.isSoftware?'العالم جاهز · عرض ثلاثي الأبعاد خفيف':'العالم جاهز · تحكم بالماوس ولوحة المفاتيح أو اللمس';el('startBtn').disabled=false;el('startBtn').textContent=wordCount()?'أكمل رحلتك ←':'ابدأ الاستكشاف ←';document.body.dataset.ready='true';requestAnimationFrame(frame);
